### ISSUE TITLE
Testing the repetability of the flight

### ISSUE THREAD

**Issue by Archimonde666** [Archimonde666/Challenge-drone-EA#10]
@pbag47
Imagine we put a window for the drone to cross in the arena, and an infrared marker on a Tello.
Could we use the swarm installation to monitor the track of the Tello ? And how much time would you actually need to setup an experiment link that ? Only the infrared tracking setup.
The expected output would be a CSV with time and positions i believe.

I'd imagine i can code a little program that passes the windows again and again by turning 180° each time with an ARUCO-CODE on each side.

We could then make a real statistical analysis on those data and choose safe but minimal accuracy we can expect from the drone.
I also expect less precision with lower battery => we will have to take that into account

**Comment by pbag47** [comment]
@Archimonde666
The MoCap tracking program already exists for Crazyflie UAVs. It can easily be refactored to track the Tello instead.
The only issue to seriously take into consideration would come from a timescale mismatch between the MoCap and the Tello logging program (the MoCap runs on its own PC so it won't be easy to merge its output csv file with the logger output of the Tello)

**Comment by Archimonde666** [comment]
I dont think we need to merge those data, we can just assume during a test the battery goes from full (start) to depleted (end) linearly.
=> this way this would be very easy to only process the CSV from your system.

I will program a little squary motion inside the arena to test the repetability of the flight itself.
Next we will be able to test the "controler" repetability with a real gate with an ARUCO-CODE and isolate the induced error of our automatic controler itself (by substracting repetability of the internals of the Tello first).
=> this way we will be able to test for different automatic controler repetability if needed

Could you look into fixing an infrared marker on a Tello and preparing the software ?

**Comment by pbag47** [comment]
@Archimonde666 

All set, ready to log.

**Comment by pbag47** [comment]
[mesures_repetabilite_Tello.ods](https://github.com/Archimonde666/Challenge-drone-EA/files/9703242/mesures_repetabilite_Tello.ods)
