### ISSUE TITLE
Camera sight angles measurement

### ISSUE THREAD

**Issue by pbag47** [Archimonde666/Challenge-drone-EA#26]
This information could be useful to approximate distances by comparing the ARUCO markers real size with the measured size on the camera frame (neglecting the lens distortion is a brutal approximation, especially near the borders of the screen, but it can still provide a good distance reference between the UAV and the marker in sight).
The sight angles (vertical and horizontal) might be different between the simulator and the real Tello camera.

**Comment by pbag47** [comment]
Standby while #27 is still active

**Comment by pbag47** [comment]
Real Tello horizontal sight angles measurement :


![sight horizontal angle measurement 2](https://user-images.githubusercontent.com/102966189/194820517-102a04d5-5170-44d8-a445-cdb8270324c7.png)

**Comment by pbag47** [comment]
Real Tello vertical sight angle measurement : 


![sight vertical angle offset measurement 2](https://user-images.githubusercontent.com/102966189/194817988-74505ac3-8780-4a7c-a712-89ffddbac1fe.png)

**Comment by Archimonde666** [comment]
Why accomodate with the lens distortion doing nothing ?

I propose we compute these local distortion based of a picture taken with the Tello of a regular grid

**Comment by pbag47** [comment]
Real Tello vertical sight angle offset (relative to horizontal line) measurement : 

![sight vertical angle offset measurement](https://user-images.githubusercontent.com/102966189/194248096-5fa80523-9cc6-4d62-b983-38bb492cc591.png)
