### ISSUE TITLE
Image recognition test program with embedded camera

### ISSUE THREAD

**Issue by Archimonde666** [Archimonde666/Challenge-drone-EA#5]
```
Traceback (most recent call last):
  File "C:\Users\vincent.videlier\Documents\GitHub\Challenge-drone-EA\main_test_aruco_code.py", line 53, in <module>
    run()
  File "C:\Users\vincent.videlier\Documents\GitHub\Challenge-drone-EA\main_test_aruco_code.py", line 23, in run
    frame = ReadCAM.run()
  File "C:\Users\vincent.videlier\Documents\GitHub\Challenge-drone-EA\subsys_read_cam.py", line 16, in run
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
```

**Comment by Archimonde666** [comment]
concerns 
https://github.com/Archimonde666/Challenge-drone-EA/blob/main/main_test_aruco_code.py

**Comment by pbag47** [comment]
To my understanding, this module is meant to use a webcam video input in order to test the Aruco code detection without using the flight simulator.
Connecting a webcam might then solve this exception (or might not, I don't know).

**Comment by Archimonde666** [comment]
Alright => i then change this issue to feature request : i need a program to test the ARUCO code recognition with embedded camera of the tello, but without the motor functionning not to hurt myself ^.^

**Comment by Archimonde666** [comment]
I'll do that

**Comment by Archimonde666** [comment]
It's solved, juste use manual main and don't hit take off button !
